version: '2'

services:

  collector:
    build: ./collector
    image: 860498507463.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/collector
    depends_on: 
      - archiver
    environment: 
      - SEARCH_TERMS=lol
      - ARCHIVE_ENDPOINT=http://localhost:8080 
      - AWS_REGION=eu-west-1
    volumes:
      - $HOME/.aws:/root/.aws
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: /rpc-demo/collector

  archiver: 
    build: ./archiver
    image: 860498507463.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/archiver
    environment: 
      - KINESIS_STREAM_NAME=tweets
      - AWS_REGION=eu-west-1
    ports: 
      - "8080:8080"
    volumes:
      - $HOME/.aws:/root/.aws
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: /rpc-demo/archiver
      
