version: '2'

services:

  collector:
    build: ./collector
    image: 860498507463.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/collector
    depends_on: 
      - archiver
    environment: 
      - SEARCH_TERMS="aws cloud"
      - ARCHIVE_ENDPOINT=http://archiver:8080 
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

  archiver: 
    build: ./archiver
    image: 860498507463.dkr.ecr.eu-west-1.amazonaws.com/rpc-demo/archiver
    environment: 
      - KINESIS_STREAM_NAME=tweets
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    ports: 
      - "8080:8080"

