// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twitterarchive.proto

/*
Package twitterarchive is a generated protocol buffer package.

It is generated from these files:
	twitterarchive.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
*/
package twitterarchive

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateResponse struct {
	Sequence string `protobuf:"bytes,1,opt,name=sequence" json:"sequence,omitempty"`
	Shard    string `protobuf:"bytes,2,opt,name=shard" json:"shard,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateResponse) GetSequence() string {
	if m != nil {
		return m.Sequence
	}
	return ""
}

func (m *CreateResponse) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRequest)(nil), "twitterarchive.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "twitterarchive.CreateResponse")
}

func init() { proto.RegisterFile("twitterarchive.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x29, 0xcf, 0x2c,
	0x29, 0x49, 0x2d, 0x4a, 0x2c, 0x4a, 0xce, 0xc8, 0x2c, 0x4b, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x43, 0x15, 0x55, 0xb2, 0xe5, 0xe2, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x73, 0x53, 0x8b, 0x8b, 0x13, 0xd3,
	0x53, 0x25, 0x98, 0xc0, 0xc2, 0x30, 0xae, 0x92, 0x13, 0x17, 0x1f, 0x4c, 0x7b, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0xaa, 0x90, 0x14, 0x17, 0x47, 0x31, 0xc8, 0xa8, 0xbc, 0x64, 0x98, 0x19, 0x70, 0xbe,
	0x90, 0x08, 0x17, 0x6b, 0x71, 0x46, 0x62, 0x51, 0x0a, 0xd4, 0x14, 0x08, 0xc7, 0x28, 0x9a, 0x8b,
	0x2f, 0x04, 0xe2, 0x28, 0x47, 0x88, 0xa3, 0x84, 0x3c, 0xb9, 0xd8, 0x20, 0xa6, 0x0a, 0xc9, 0xea,
	0xa1, 0xf9, 0x02, 0xc5, 0xb1, 0x52, 0x72, 0xb8, 0xa4, 0x21, 0x8e, 0x51, 0x62, 0x48, 0x62, 0x03,
	0x7b, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x56, 0xcf, 0x91, 0x0e, 0x01, 0x00, 0x00,
}
